// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnkxaezxodhvrxameair.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJua3hhZXp4b2RodnJ4YW1lYWlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NjIxODIsImV4cCI6MjA2OTIzODE4Mn0.12Xvdm0bqy_f2RjSq2YLN1xmTFjEclPE5JhbD8zOlxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});